### ISSUE TITLE
ReflectionException

### ISSUE THREAD

**Issue by tanerincode** [ijeffro/laravel-cities#3]
Laravel : 5.5
 Composer version :  1.5.2
 PHP : 7.1.8

when I apply the steps one by one I get an error like this:
command :: $ php artisan cities:migration

[ReflectionException]
 Method ijeffro\Cities\MigrationCommand::handle() does not exist

**Comment by ijeffro** [comment]
Awesome, I'll need to change the fire method to handle on the Migration Command. You can do this locally by navigating to laravel_app/vendor/ijeffro/laravel-cities/src/commands/MigrationCommand.php and amending line 41 from "public function fire()" "to public function handle()".

**Comment by ijeffro** [comment]
https://github.com/ijeffro/laravel-cities/commit/83d9708b7565dc23e659bafa2433655d216236af

**Comment by tanerincode** [comment]
thank you. I will make the necessary arrangements.

**Comment by ijeffro** [comment]
That caused new errors in the end, I created an alias instead; that works fine now.
